### ISSUE TITLE
Is this the latest release?

### ISSUE THREAD

**Issue by jbowles** [PhDP/alchemy2#1]
@PhDP I've been looking into Statistical Relational Learning and came across the alchemy project hosted on google code archive. Their export tool is now expired. 

I'm curious if what you have here was up to date the last latest release, or if there is an `official` repo anywhere?

Thanks in advance.

**Comment by PhDP** [comment]
Hi @jbowles 

Yes it's the latest release (with a few minor fixes), the official repo was on google code. Alchemy remains the most complete implementation of markov logic (it does inference but also weight and structure learning), but if you're only interested in inference, I suggest you take a look at the Java-based Tuffy (http://i.stanford.edu/hazy/tuffy/) or wait for me to finish my C++/CUDA implementation :P

Cheers,

Philippe

**Comment by jbowles** [comment]
Oh great, thanks. I'm more on the c++ side of the fence ;)  Adding the manual and even the bare bones examples is great though, thanks.
